import type * as monaco from "monaco-editor";

export const monacoTheme: monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "keyword", foreground: "3ECF8E", fontStyle: "bold" },
    { token: "operator.sql", foreground: "707070" },
    { token: "string.sql", foreground: "F5A623" },
    { token: "number", foreground: "60A5FA" },
    { token: "comment", foreground: "525252", fontStyle: "italic" },
    { token: "identifier", foreground: "ededed" },
    { token: "predefined.sql", foreground: "3ECF8E" },
    { token: "operator.keyword", foreground: "3ECF8E", fontStyle: "bold" },
  ],
  colors: {
    "editor.background": "#171717",
    "editor.foreground": "#ededed",
    "editorCursor.foreground": "#3ECF8E",
    "editor.lineHighlightBackground": "#1f1f1f",
    "editorLineNumber.foreground": "#525252",
    "editorLineNumber.activeForeground": "#707070",
    "editor.selectionBackground": "#323232",
    "editor.inactiveSelectionBackground": "#2a2a2a",
    "editorIndentGuide.background": "#2e2e2e",
    "editorWidget.background": "#1f1f1f",
    "editorWidget.border": "#2e2e2e",
    "editorSuggestWidget.background": "#1f1f1f",
    "editorSuggestWidget.border": "#2e2e2e",
    "editorSuggestWidget.selectedBackground": "#323232",
    "editorSuggestWidget.highlightForeground": "#3ECF8E",
    "input.background": "#171717",
    "input.border": "#2e2e2e",
    focusBorder: "#3ECF8E",
    "scrollbarSlider.background": "#40404080",
    "scrollbarSlider.hoverBackground": "#52525280",
    "scrollbarSlider.activeBackground": "#52525280",
  },
};

export const SQL_KEYWORDS = [
  "SELECT",
  "FROM",
  "WHERE",
  "INSERT",
  "INTO",
  "VALUES",
  "UPDATE",
  "SET",
  "DELETE",
  "CREATE",
  "TABLE",
  "ALTER",
  "DROP",
  "INDEX",
  "VIEW",
  "JOIN",
  "INNER",
  "LEFT",
  "RIGHT",
  "OUTER",
  "FULL",
  "CROSS",
  "ON",
  "AS",
  "AND",
  "OR",
  "NOT",
  "IN",
  "EXISTS",
  "BETWEEN",
  "LIKE",
  "ILIKE",
  "IS",
  "NULL",
  "TRUE",
  "FALSE",
  "ORDER",
  "BY",
  "ASC",
  "DESC",
  "LIMIT",
  "OFFSET",
  "GROUP",
  "HAVING",
  "UNION",
  "ALL",
  "DISTINCT",
  "CASE",
  "WHEN",
  "THEN",
  "ELSE",
  "END",
  "COUNT",
  "SUM",
  "AVG",
  "MIN",
  "MAX",
  "COALESCE",
  "CAST",
  "PRIMARY",
  "KEY",
  "FOREIGN",
  "REFERENCES",
  "CONSTRAINT",
  "DEFAULT",
  "NOT",
  "CHECK",
  "UNIQUE",
  "WITH",
  "RECURSIVE",
  "RETURNING",
  "SERIAL",
  "BIGSERIAL",
  "TEXT",
  "VARCHAR",
  "INTEGER",
  "INT",
  "BIGINT",
  "BOOLEAN",
  "TIMESTAMP",
  "DATE",
  "TIME",
  "NUMERIC",
  "DECIMAL",
  "FLOAT",
  "DOUBLE",
  "JSON",
  "JSONB",
  "UUID",
  "ARRAY",
  "BEGIN",
  "COMMIT",
  "ROLLBACK",
  "TRANSACTION",
  "GRANT",
  "REVOKE",
  "TRUNCATE",
  "EXPLAIN",
  "ANALYZE",
  "VACUUM",
];
